import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider as RadixProvider } from "@radix-ui/react-tooltip";
import { Toaster } from "sonner";
import UserProvider from "@/app/provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI Interview Schedule Voice Agent",
  description: "Generated by create next app",
};  

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RadixProvider>
          <UserProvider>
            {children}
            <Toaster/>
          </UserProvider>
        </RadixProvider>
      </body>
    </html>
  );
}
